on:
  workflow_call:
    inputs:
      derivations:
        required: true
        type: string
    secrets:
      CACHIX_AUTH_TOKEN:
        required: true
jobs:
  build:
    name: build ${{ matrix.derivation.name }} ${{ matrix.derivation.system }}
    strategy:
      matrix:
        derivation: ${{ fromJson(inputs.derivations) }}
    runs-on: ${{ (matrix.deriation.system == 'aarch64-linux' && 'ubuntu-24.04-arm')  || (matrix.derivation.system == 'x86_64-linux' && 'ubuntu-latest') || 'unknown' }}
    steps:
      - uses: cachix/install-nix-action@v27
        if: ${{ ! matrix.derivation.isCached }}
      - uses: cachix/cachix-action@v14
        with:
          name: sonos
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
        if: ${{ ! matrix.derivation.isCached }}
      - name: build ${{ matrix.derivation.attr }}
        run: nix-build ${{ matrix.derivation.drvPath }}
        if: ${{ ! matrix.derivation.isCached }}
